### PR TITLE
builder/iso: Use `--audio-driver` instead of the deprecated `--audio` parameter

### PR DESCRIPTION
**Pull request by jlduran**
--audio is deprecated, use --audio-driver instead.

### CODE REVIEW

**Comment by nywilken** [comment]
Good to know, thanks! We'll try to take a look for the next release. 

Do you have a link to the documentation where the audio flag was deprecated? 

It would be nice to include that in the documentation, release notes.

**Comment by jlduran** [comment]
> Do you have a link to the documentation where the audio flag was deprecated?

Yes!
https://www.virtualbox.org/wiki/Changelog#v6
> Audio: The "--audio" option in VBoxManage is now marked as deprecated; please use "--audio-driver" and "--audio-enabled" instead. This will allow more flexibility when changing the driver and/or controlling the audio functionality

**Review by nywilken — APPROVED** [review]
This looks good and works as expected. Thank you for the update.

**Comment by lorengordon** [comment]
@nywilken @jlduran  FYI, this breaks build using VirtualBox 6.1.x, which is still supported and only offers `--audio`. See #139

**Comment by jlduran** [comment]
> @nywilken @jlduran FYI, this breaks builds using VirtualBox 6.1.x, which is still supported and only offers `--audio`. See #139

Ah... sorry, I hate when that happens. But, VirtualBox 6.1 has an EOL date of 2024/01. I would suggest pinning the plugin to the latest working version (i.e. 1.0.5).

**Comment by lorengordon** [comment]
Yeah, that's what I did. It's frustrating because the Ubuntu repos still only package Virtualbox 6.1, so there is no easy/default path to use 7.0. :( Where do you see the EOL for 6.1? The issue I linked was claiming that it is still supported...

**Comment by jlduran** [comment]
> Where do you see the EOL for 6.1? The issue I linked was claiming that it is still supported...

https://www.virtualbox.org/wiki/Download_Old_Builds

**Comment by Stromweld** [comment]
you can also add the virtualbox repo for debian/ubuntu, rhel, etc... and upgrade to virtualbox 7 through your package manager. https://www.virtualbox.org/wiki/Linux_Downloads

**Pull request merged**
